filter:
    paths:
        - 'htdocs/*'
        - 'htdocs2/*'
        - 'local/*'
    excluded_paths:
        - 'bin/*'
        - 'doc/*'
        - 'htdocs/resource2/config2/*'
        - 'htdocs/resource2/tinymce/*'
        - 'htdocs/resource2/ocstyle/js/communicator-api/*'
        - 'htdocs/resource2/ocstyle/js/enlargeit/*'
        - 'htdocs/templates2/*'
    dependency_paths:
        - 'htdocs/vendor/*'
        - 'htdocs2/vendor/*'

checks:
    php: true
    javascript: true
